
networks:
  webflux-ai-net:
    driver: bridge

services:
  mariadb:
    image: mariadb:11.8
    container_name: webflux-ai-mariadb
    restart: unless-stopped
    networks:
      - webflux-ai-net
    environment:
      MARIADB_ROOT_PASSWORD: root1234
      MARIADB_DATABASE: demo
      MARIADB_USER: demo
      MARIADB_PASSWORD: demo1234
    ports:
      - "33060:3306"
    volumes:
      - webflux_ai_mariadb_data:/var/lib/mysql

volumes:
  webflux_ai_mariadb_data: